version: '3.0'

services:
  translation_postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=translation_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - translations_data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - translation_memory_data:/bitnami/redis/data

volumes:
  translations_data:
  translation_memory_data:
